apiVersion : apps/v1
kind: Deployment
metadata:
  name: fishlienapro 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishlienapro
  template:
    metadata:
      labels:
        app: fishlienapro 
    spec:
      containers:
        - name: fishlienapro 
          image: a2conreg.azurecr.io/fishlienapro
          ports:
          - containerPort: 8080